### ISSUE TITLE
Опечатка в README

### ISSUE THREAD

**Issue by anchupin** [TinkoffCreditSystems/vkarmane-sdk-android#1]
В файле README.md в блоке "Пример получения паспортных данных пользователя"

    // 1. Создаем и сохраняем ключи
    val keys = VKarmaneSDK.generateKeys()

    // 2. Создаем ссылку
    val vkarmaneLink = VKarmaneSDK.getDocumentsLinkBuilder()
            .setMultiChoice(multiChoice.isChecked)
            .setKinds(docs)
            .setXSource("Vkarmane Test")
            .setXCancelLink("vkarmanesdkexample://vkarmane-sdk-cancel")
            .setXErrorLink("vkarmanesdkexample://vkarmane-sdk-error")
            .setXSuccessLink("vkarmanesdkexample://vkarmane-sdk-success")
            .setPublicKey(keys.publicKey)
            .build()

    // 3. Переходим
    val i = Intent(Intent.ACTION_VIEW)
    i.data = Uri.parse(link)
    startActivity(i)

    // 4. Получаем и расшифровываем данные изначально сгенерированным `keys.privateKey`
    intent.data?.let { uri ->
        val privateKey = keys.getPrivateKey()
        json = VKarmaneSDK.getJsonFromLink(uri, privateKey)
    }

Создание ссылки во 2 пункте происходит в переменную `vkarmaneLink`, а переход по ссылке осуществляется с переменной `link` в строке  ` i.data = Uri.parse(link)`. Немного вводит в заблуждение при первом прочтении документации.

**Comment by eukleshnin** [comment]
Спасибо, исправлено.
